/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.CurrentSesionController;
import controllers.ProductsController;
import controllers.ProvidersController;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos Andres Cordoba
 */
public class ProvidersView extends javax.swing.JFrame {

    private Object[][] rows;
    private int userIdLogged;
    private ProvidersController ctrlProvider = new ProvidersController();
    private CHAFDependenciesViews  dp = new CHAFDependenciesViews ();

    /**
     * Creates new form ProvidersView
     */
    public ProvidersView() {
        initComponents();
    }
    
     public void setUserIdLogged(int id){
      this.userIdLogged = id;
    }
    
    public void setInfoUser(){
      CurrentSesionController sesion = new CurrentSesionController(this.userIdLogged);
      this.nameUser.setText(sesion.getName());
      this.rolUser.setText(sesion.getRol());
    }
    public Object[][] initRows(int filas){
        //// variables para traer el login del usuario, 
        ///  ya que el metodo getUserForTable pide como parametros
        ///  el indice de la columna de la consulta y un iterador
        /**/ int providerTypeDoc = 1;
        /**/ int providerNumDoc = 2;
        /**/ int nameProvider = 4;
        this.rows = new Object[filas][6];
        for(int i = 0;i < filas;i++){
            for(int j = 0;j< 6 ;j++){
               switch(j){
                       case 0: rows[i][j] = this.ctrlProvider.getProvidersForTable(providerTypeDoc, i);
                       break;
                       case 1: rows[i][j] = this.ctrlProvider.getProvidersForTable(providerNumDoc, i);
                       break;    
                       case 2: rows[i][j] = this.ctrlProvider.getProvidersForTable(nameProvider, i);
                       break;
                       case 3: rows[i][j] = this.dp.getEditar();
                       break;
                       case 4: rows[i][j] = this.dp.getEliminar();
                       break;
                       case 5: rows[i][j] = this.dp.getActivar();
                       break;
               }
            }
        }
        return rows;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        materialButton1 = new libraries.MaterialButton();
        rolUser = new javax.swing.JLabel();
        nameUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            initRows(this.ctrlProvider.getUsersOnTable())
            ,
            new String [] {
                "Tipo Id", "Num Id","Razon Social", "Editar","Desactivar","Activar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false,false, false,false,false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }

        });
        this.jTable1.getColumn("Editar").setCellRenderer(this.dp.getRender());
        this.jTable1.getColumn("Editar").setMaxWidth(this.dp.getSizeColumn());
        this.jTable1.getColumn("Desactivar").setCellRenderer(this.dp.getRender());
        this.jTable1.getColumn("Desactivar").setMaxWidth(this.dp.getSizeColumn() + 20);
        this.jTable1.getColumn("Activar").setCellRenderer(this.dp.getRender());
        this.jTable1.getColumn("Activar").setMaxWidth(this.dp.getSizeColumn());
        this.jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        materialButton1.setBackground(new java.awt.Color(119, 177, 236));
        materialButton1.setText("Registrar Proveedor");
        materialButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                materialButton1MouseClicked(evt);
            }
        });
        materialButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButton1ActionPerformed(evt);
            }
        });

        rolUser.setText("jLabel2");

        nameUser.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(materialButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rolUser)
                            .addComponent(nameUser))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(nameUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rolUser)
                .addGap(18, 18, 18)
                .addComponent(materialButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = this.jTable1.getSelectedRow();
        int col = this.jTable1.getSelectedColumn();     
        if(col == 3){
            System.out.println("col == 3 row ="+row);
            TercerosRegisterView creacionTercero = new TercerosRegisterView("PROVEEDOR",1);
            Object id = this.jTable1.getModel().getValueAt(row, 1);
            ArrayList <String> datos = this.ctrlProvider.showRegisterProvider(Integer.parseInt(id.toString()));
            creacionTercero.setNumeroIdentificacion(datos.get(1));
            creacionTercero.setUserDir(datos.get(2));
            creacionTercero.setNombreUser(datos.get(3));
            creacionTercero.setTelUser(datos.get(4));
            creacionTercero.setVisible(true);                    
        }

        if(col == 5){

          System.out.println("col = 5 row ="+row);
        }
        if(col== 3){
            System.out.println("col = 3 row ="+row);
            
        }
//          if(productCtl == null) productCtl = new ProductsController();
//          if(typeButton.toString().substring(20, 27).equals("elimina")){
//            seleccion = JOptionPane.showConfirmDialog(null, "¿Desea desactivar el producto?", "Desactivar producto", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
//            ArrayList<String> result = productCtl.delete(Integer.parseInt(id));
//            JOptionPane.showMessageDialog(null,result.get(1) );  
//          }
//          else{
//            seleccion = JOptionPane.showConfirmDialog(null, "¿Desea activar el producto?", "Activar producto", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
//            ArrayList<String> result = productCtl.activate(Integer.parseInt(id));
//            JOptionPane.showMessageDialog(null,result.get(1) );
//          }

        
    }//GEN-LAST:event_jTable1MouseClicked

    private void materialButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_materialButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_materialButton1MouseClicked

    private void materialButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println("[TercerosRegisterView]: entrando a creacion de Usuarios");
        TercerosRegisterView creacionTercero = new TercerosRegisterView("PROVEEDOR",0);
        creacionTercero.setVisible(true);
        creacionTercero.setLayout(null);
        creacionTercero.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_materialButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProvidersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProvidersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProvidersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProvidersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProvidersView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private libraries.MaterialButton materialButton1;
    private javax.swing.JLabel nameUser;
    private javax.swing.JLabel rolUser;
    // End of variables declaration//GEN-END:variables
}
