/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import libraries.TextPrompt;



/**
 *
 * @author david
 */
public class TercerosRegisterView extends javax.swing.JFrame {

    /**
     * Creates new form UserRegisterView
     */
    private TextPrompt numeroIdentificacion,direccion,nombreCompleto,telefono;
    
    public TercerosRegisterView() {
        
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tipoDoc = new views.Input();
        jComboBox1 = new javax.swing.JComboBox<>();
        nomCompleto = new views.Input();
        inputUser2 = new javax.swing.JTextField();
        direction = new views.Input();
        inputUser4 = new javax.swing.JTextField();
        numDoc = new views.Input();
        inputUser5 = new javax.swing.JTextField();
        phone = new views.Input();
        inputUser6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "NIT", "TI", "AS", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tipoDocLayout = new javax.swing.GroupLayout(tipoDoc);
        tipoDoc.setLayout(tipoDocLayout);
        tipoDocLayout.setHorizontalGroup(
            tipoDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tipoDocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, 0, 314, Short.MAX_VALUE)
                .addContainerGap())
        );
        tipoDocLayout.setVerticalGroup(
            tipoDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tipoDocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1)
                .addContainerGap())
        );

        inputUser2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        inputUser2.setForeground(new java.awt.Color(134, 134, 134));
        inputUser2.setToolTipText("");
        direccion = new TextPrompt("Direccion",this.inputUser2);
        inputUser2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        inputUser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUser2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nomCompletoLayout = new javax.swing.GroupLayout(nomCompleto);
        nomCompleto.setLayout(nomCompletoLayout);
        nomCompletoLayout.setHorizontalGroup(
            nomCompletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomCompletoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputUser2, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
        );
        nomCompletoLayout.setVerticalGroup(
            nomCompletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomCompletoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputUser2)
                .addContainerGap())
        );

        inputUser4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        inputUser4.setForeground(new java.awt.Color(134, 134, 134));
        inputUser4.setToolTipText("");
        nombreCompleto = new TextPrompt("Nombres y Apellidos",this.inputUser4);
        inputUser4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        inputUser4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUser4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout directionLayout = new javax.swing.GroupLayout(direction);
        direction.setLayout(directionLayout);
        directionLayout.setHorizontalGroup(
            directionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(directionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputUser4, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
        );
        directionLayout.setVerticalGroup(
            directionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(directionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputUser4)
                .addContainerGap())
        );

        inputUser5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        inputUser5.setForeground(new java.awt.Color(134, 134, 134));
        inputUser5.setToolTipText("");
        numeroIdentificacion = new TextPrompt("Numero de documento",this.inputUser5);
        inputUser5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        inputUser5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUser5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout numDocLayout = new javax.swing.GroupLayout(numDoc);
        numDoc.setLayout(numDocLayout);
        numDocLayout.setHorizontalGroup(
            numDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numDocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputUser5, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
        );
        numDocLayout.setVerticalGroup(
            numDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numDocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputUser5)
                .addContainerGap())
        );

        inputUser6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        inputUser6.setForeground(new java.awt.Color(134, 134, 134));
        inputUser6.setToolTipText("");
        this.telefono = new TextPrompt("Telefono",this.inputUser6);
        inputUser6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        inputUser6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUser6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout phoneLayout = new javax.swing.GroupLayout(phone);
        phone.setLayout(phoneLayout);
        phoneLayout.setHorizontalGroup(
            phoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phoneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputUser6, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
        );
        phoneLayout.setVerticalGroup(
            phoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phoneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputUser6)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(tipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(numDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nomCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(direction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputUser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUser2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUser2ActionPerformed

    private void inputUser4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUser4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUser4ActionPerformed

    private void inputUser5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUser5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUser5ActionPerformed

    private void inputUser6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUser6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUser6ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TercerosRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TercerosRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TercerosRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TercerosRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TercerosRegisterView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private views.Input direction;
    private views.Input input3;
    private javax.swing.JTextField inputUser1;
    private javax.swing.JTextField inputUser2;
    private javax.swing.JTextField inputUser4;
    private javax.swing.JTextField inputUser5;
    private javax.swing.JTextField inputUser6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private views.Input nomCompleto;
    private views.Input numDoc;
    private views.Input phone;
    private views.Input tipoDoc;
    // End of variables declaration//GEN-END:variables
}
